[package]
name = "MinING_compiler_project"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
logos="0.14.2"
once_cell = "1.20.2"
lalrpop-util = { version = "0.22.0", features = ["lexer", "unicode"] }
regex = "1"

[build-dependencies]
lalrpop = "0.22.0"